services:
  web_server_nginx:
    build: ./web-server
    container_name: web_server_nginx
    volumes:
      - ./web-server/conf/default.development.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8003:8000
    depends_on:
      - client_web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - network

  client_web:
    build: .
    container_name: client_web
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 8004
    expose:
      - 8004
    volumes:
      - client_web_node_modules:/app/node_modules
      - ./:/app
    networks:
      - network

volumes:
  client_web_node_modules:

networks:
  network:
    driver: bridge
