services:
  attribution_system_web_server_nginx:
    build: ./infrastructures/nginx
    platform: linux/amd64
    container_name: attribution_system_web_server_nginx
    restart: unless-stopped
    volumes:
      - ./client/dist:/var/www/public
      - ./infrastructures/nginx/conf/default.production.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    depends_on:
      - attribution_system_api_ml_flask
      - attribution_system_database_pocketbase
      - attribution_system_api_core_express
      - attribution_system_client_react
    extra_hosts:
      - host.docker.internal:172.18.0.1
    networks:
      - network

  attribution_system_client_react:
    build: ./client
    platform: linux/amd64
    container_name: attribution_system_client_react
    restart: on-failure
    working_dir: /app
    environment:
      - VITE_CORE_API_BASE_URL=https://core.attribution-system.org
    volumes:
      - ./client:/app
      - volume_client_react_node_modules:/app/node_modules
    depends_on:
      - attribution_system_api_core_express
    extra_hosts:
      - host.docker.internal:172.18.0.1
    networks:
      - network

  attribution_system_database_pocketbase:
    build: ./infrastructures/pocketbase
    platform: linux/amd64
    container_name: attribution_system_database_pocketbase
    restart: unless-stopped
    working_dir: /pb
    volumes:
      - ./infrastructures/pocketbase/data:/pb/pb_data
    expose:
      - 8001
    extra_hosts:
      - host.docker.internal:172.18.0.1
    networks:
      - network

  attribution_system_api_ml_flask:
    build:
      context: ./api/ml
      dockerfile: ./Dockerfile.production
    platform: linux/amd64
    container_name: attribution_system_api_ml_flask
    restart: unless-stopped
    working_dir: /api
    expose:
      - 8002
    extra_hosts:
      - host.docker.internal:172.18.0.1
    networks:
      - network

  attribution_system_api_core_express:
    build: ./api/core
    platform: linux/amd64
    container_name: attribution_system_api_core_express
    restart: unless-stopped
    working_dir: /app
    environment:
      - POCKETBASE_URL=https://pocketbase.attribution-system.org
      - API_ML_URL=https://ml.attribution-system.org
      - POCKETBASE_ADMIN_EMAIL=admin@email.com
      - POCKETBASE_ADMIN_PASSWORD=adminpassword
    volumes:
      - volume_api_core_express_node_modules:/app/node_modules
    expose:
      - 8003
    depends_on:
      - attribution_system_api_ml_flask
      - attribution_system_database_pocketbase
    extra_hosts:
      - host.docker.internal:172.18.0.1
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  volume_api_core_express_node_modules:
  volume_client_react_node_modules:
